In [1]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]=5
print(a)


b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [6]:
array_1d = np.array([1,2,3,4])
array_1by4 = np.array([1,2,3,4])
large_array = np.array([i for i in range(400)])
large_array = large_array.reshape((20,20))

from_list = np.array([1,2,3])
from_list_2d = np.array([[1,2,3.0], [4,5,6]])
from_list_bad_type=np.array([1,2,3,'a'])

print(f'Data type of integer is {from_list.dtype}')
print(f'Data type of float is {from_list_2d.dtype}')

Data type of integer is int32
Data type of float is float64


In [13]:
array_1d + 5

array([6, 7, 8, 9])

In [15]:
array_1d * 5

array([ 5, 10, 15, 20])

In [17]:
print(large_array)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219]
 [220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235

In [19]:
np.sqrt(array_1d)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [21]:
np.power(array_1d,2)

array([ 1,  4,  9, 16], dtype=int32)

In [23]:
np.exp(array_1d)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [24]:
np.log(array_1d)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
import pandas as pd
data=pd.read_csv('ds_salaries.csv', index_col=0)
data_short = data[:20][["work_year","salary","salary_in_usd","remote_ratio","company_size"]]
data_short

work_year    salary  salary_in_usd  remote_ratio company_size
0        2020     70000          79833             0            L
1        2020    260000         260000             0            S
2        2020     85000         109024            50            M
3        2020     20000          20000             0            S
4        2020    150000         150000            50            L
5        2020     72000          72000           100            L
6        2020    190000         190000           100            S
7        2020  11000000          35735            50            L
8        2020    135000         135000           100            L
9        2020    125000         125000            50            S
10       2020     45000          51321             0            S
11       2020   3000000          40481             0            L
12       2020     35000          39916             0            M
13       2020     87000          87000           100            L
14       2020     85000          85000           100            L
15       2020      8000           8000            50            L
16       2020   4450000          41689           100            S
17       2020    100000         114047           100            S
18       2020    423000           5707            50            M
19       2020     56000          56000           100            M

In [30]:
print(data['salary'].describe())
data.describe()

count    6.070000e+02
mean     3.240001e+05
std      1.544357e+06
min      4.000000e+03
25%      7.000000e+04
50%      1.150000e+05
75%      1.650000e+05
max      3.040000e+07
Name: salary, dtype: float64


work_year        salary  salary_in_usd  remote_ratio
count   607.000000  6.070000e+02     607.000000     607.00000
mean   2021.405272  3.240001e+05  112297.869852      70.92257
std       0.692133  1.544357e+06   70957.259411      40.70913
min    2020.000000  4.000000e+03    2859.000000       0.00000
25%    2021.000000  7.000000e+04   62726.000000      50.00000
50%    2022.000000  1.150000e+05  101570.000000     100.00000
75%    2022.000000  1.650000e+05  150000.000000     100.00000
max    2022.000000  3.040000e+07  600000.000000     100.00000

In [31]:
data_short.to_csv('data_short.csv', index=False)

In [ ]:
data_short[(data_short['salary']>10000)]